---
- name: Deploying httpd
  hosts:
    ansible1
  tasks:
   - name:  Installing httpd
     dnf:
      name : httpd
      state: present
   - name: Activating httpd service
     service:
      name : httpd
      state: started
   - name : Activating Firewall to allow http/https
     firewalld:
      service: https
      state: enabled
      permanent: yes
      