---
- name: Removing HTTPD package
  hosts:
    ansible1
  tasks:
   - name: Disable httpd service
     service:
      name : httpd
      state : stopped
   - name: Remove httpd package
     dnf:
      name : httpd
      state : removed
   - name : Disable firewall for opened service
     firewalld:
      service: http, https
      permanent: yes
      state: disabled 
