---
kind: PersistentVolume
apiVersion: v1
metadata: 
  name: pv-volume
  labels: 
    type: local
spec: 
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  #make sure path is available in the host(minikube)
  hostPath:
    path: "/mydata"