---

- name: Ensure UFW enable and started on boot and Enable port to make them accessible.
  community.general.ufw:
    state: enabled
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - "{{ firewall_allowed_tcp_ports }} "
  notify: restart ufw firewall



  
    
  

