---
- name: Ensure firewalld is started and enable on boot
  service:
    name: firewalld
    state: "{{ firewall_state }}"
    enabled: "{{ firewall_enabled_at_boot }}"

- name: Enable port to make them accessible. (RHEL/CENTOS)
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    state: enabled
    permanent: yes
  with_items:
    - "{{ firewall_allowed_tcp_ports }}"
  notify: restart firewall